################################################################################
# PRUEBAS DE VALIDACIÓN DE CLIENTES (HU14)
#
# Este archivo cubre el flujo completo para probar la aprobación y rechazo de
# clientes pendientes por parte de un profesional.
#
# Antes de empezar, ejecutar el endpoint de inicialización para resetear la base
# de datos con los datos de prueba.
################################################################################

### Inicializar la base de datos con datos de prueba
# Ejecutar este paso antes de comenzar cualquier prueba.
POST http://localhost:3000/api/setup/database
Content-Type: application/json

{}

################################################################################
### 1. Obtener lista de usuarios pendientes
# Verificar que haya inicialmente 5 usuarios pendientes. (Va a aparecer el log en la terminal)
################################################################################

GET http://localhost:3000/api/customers/pending
x-user-id: 11

################################################################################
# FIN DEL FLUJO DE PRUEBAS
# Para volver a empezar, ejecutar nuevamente el endpoint de inicialización al comienzo del archivo.
################################################################################

POST http://localhost:3000/api/customers
Content-Type: application/json

{
  "first_name": "Juan",
  "last_name": "Pérez",
  "email": "juan@example.com",
  "password": "123456",
  "phone": "3411234567",
  "birth_date": "1990-05-10",
  "role": "customer"
}

#####

DELETE http://localhost:3000/api/customers/1
x-user-id: 11
